/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.MonitoresController;
import javax.swing.JOptionPane;


/**
 *
 * @author David Sanchez Avila
 */
public class VistaFormularioMod extends javax.swing.JFrame {

    private final MonitoresController monitoresController;
    /**
     * Creates new form VistaFormulario
     */
    public VistaFormularioMod() {
        initComponents();
        
        monitoresController = new MonitoresController();
        
        // Boton por defecto
        getRootPane().setDefaultButton(botonModificar);
        
        // Redondeos
        panelVolver.putClientProperty("FlatLaf.style", "arc:50");
        botonModificar.putClientProperty( "FlatLaf.style", "arc: 25" );
        textFieldNombre.putClientProperty("FlatLaf.style", "arc: 20");
        textFieldApellidos.putClientProperty("FlatLaf.style", "arc: 20");
        textFieldActividad.putClientProperty("FlatLaf.style", "arc: 20");
        textFieldId.putClientProperty("FlatLaf.style", "arc: 20");
        
        // Placeholders
        textFieldNombre.putClientProperty("JTextField.placeholderText", "Inserte el nombre");
        textFieldApellidos.putClientProperty("JTextField.placeholderText", "Inserte los apellidos");
        textFieldActividad.putClientProperty("JTextField.placeholderText", "Inserte la actividad");
        textFieldId.putClientProperty("JTextField.placeholderText", "Inserte el id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldApellidos = new javax.swing.JTextField();
        textFieldActividad = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelActividad = new javax.swing.JLabel();
        botonModificar = new javax.swing.JButton();
        panelVolver = new javax.swing.JPanel();
        labelVolver = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VistaFormularioMod");
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldNombre.setToolTipText("Inserte el nombre del monitor");
        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });
        panelFondo.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 184, -1));

        textFieldApellidos.setToolTipText("Inserte los apellidos del monitor");
        textFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidosActionPerformed(evt);
            }
        });
        panelFondo.add(textFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 184, -1));

        textFieldActividad.setToolTipText("Inserte el nombre de la actividad");
        textFieldActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActividadActionPerformed(evt);
            }
        });
        panelFondo.add(textFieldActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 184, -1));

        labelNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre");
        panelFondo.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        labelApellidos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        labelApellidos.setText("Apellidos");
        panelFondo.add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        labelActividad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelActividad.setForeground(new java.awt.Color(255, 255, 255));
        labelActividad.setText("Actividad");
        panelFondo.add(labelActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        botonModificar.setBackground(new java.awt.Color(181, 2, 2));
        botonModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setToolTipText("Pulse para actualizar los campos");
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        panelFondo.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        panelVolver.setBackground(new java.awt.Color(255, 255, 255));
        panelVolver.setToolTipText("Pulse para volver a Monitores");
        panelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVolverMouseClicked(evt);
            }
        });

        labelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFondo.add(panelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        labelId.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setText("Id");
        panelFondo.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        textFieldId.setToolTipText("Inserte el id");
        textFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdActionPerformed(evt);
            }
        });
        panelFondo.add(textFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 184, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void textFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidosActionPerformed

    private void textFieldActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActividadActionPerformed

    /**
     * Metodo que recoge los datos de los textfields y llama al método actualizar monitor
     * @param evt 
     */
    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        String nombre = textFieldNombre.getText();
        String apellidos = textFieldApellidos.getText();
        String actividad = textFieldActividad.getText();
        String id = textFieldId.getText();
        int idInt = Integer.parseInt(id);
        
        // Validar que los campos no estén vacíos
        if (nombre.isEmpty() || apellidos.isEmpty() || actividad.isEmpty() || id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int filasAfectadas = monitoresController.actualizarMonitor(nombre, apellidos, actividad, idInt);
        
        if(filasAfectadas > 0)
            JOptionPane.showMessageDialog(null, "Monitor modificado con éxito");
        else
            JOptionPane.showMessageDialog(null, "Fallo al modificar el monitor");
    }//GEN-LAST:event_botonModificarActionPerformed

    /**
     * Metodo para volver a la vista monitores
     * @param evt 
     */
    private void panelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMouseClicked
        VistaMonitores monitores = new VistaMonitores();
        monitores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelVolverMouseClicked

    private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFormularioMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFormularioMod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificar;
    private javax.swing.JLabel labelActividad;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelVolver;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JTextField textFieldActividad;
    private javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
