package modelo;
// Generated 11 ene 2024 19:25:39 by Hibernate Tools 6.3.1.Final

/**
 * Actividades generated by hbm2java
 */
public class Actividades implements java.io.Serializable {

	private Integer id;
	private Reservas reservas;
	private String nombre;

	public Actividades() {
	}

	public Actividades(Reservas reservas, String nombre) {
		this.reservas = reservas;
		this.nombre = nombre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Reservas getReservas() {
		return this.reservas;
	}

	public void setReservas(Reservas reservas) {
		this.reservas = reservas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
