package modelo;
// Generated 11 ene 2024 19:25:39 by Hibernate Tools 6.3.1.Final

import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios implements java.io.Serializable {

	private Integer id;
	private Time horaInicio;
	private Time horaFin;
	private Set reservases = new HashSet(0);

	public Horarios() {
	}

	public Horarios(Time horaInicio, Time horaFin, Set reservases) {
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.reservases = reservases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Time getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Time horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Time getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Time horaFin) {
		this.horaFin = horaFin;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

}
