package modelo;
// Generated 11 ene 2024 19:25:39 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String password;
	private String email;
	private Set reservases = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String apellidos, String password, String email, Set reservases) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.password = password;
		this.email = email;
		this.reservases = reservases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

}
